version: '2'

tasks:
  test:
    desc: Run tests
    cmds:
      - go test -v ./...
  fmt:
    desc: Format go code
    cmds:
      - go fmt ./...
  build:
    desc: Build to bin
    cmds:
      - go build -o $GOPATH/bin/gorew ./main.go
  pprof:
    desc: Serve pprof
    cmds:
      - go tool pprof -http localhost:{{.PORT}} {{.FILE}}
    vars:
      PORT: 8080