version: '2'

tasks:
  test:
    cmds:
      - go test -v ./...
  fmt:
    cmds:
      - go fmt ./...
  pprof:
    cmds:
      - go tool pprof -http localhost:{{.PORT}} {{.FILE}}
    vars:
      PORT: 8080