version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/sawadashota/gocmd
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: go get -v -t -d ./...
      - run:
        name: Create binary
        command: go install
      - run:
        name: Test
        command: go test -v ./...
