version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/sawadashota/gocmd
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get -v -t -d ./...
      - run:
          name: Create binary
          command: go install
      - run:
          name: Test
          command: go test -v ./...
      - run:
          name: Create gif from gocomands/cpu.pprof
          command: go tool pprof -gif ./pprof/gocomands/cpu.pprof > ./pprof/gocomands/cpu.gif
      - run:
          name: Create gif from maindir/cpu.pprof
          command: go tool pprof -gif ./pprof/maindir/cpu.pprof > ./pprof/maindir/cpu.gif
      - store_artifacts:
          path: /go/src/github.com/sawadashota/gocmd/pprof
